"""
Project: FinTech Risk Isolation Engine
Module: NLP & ML Models Resource Module
Author: Mohit Singh
Description: Loads and caches both the deep learning FinBERT models and the 
             newly serialized Indian Market XGBoost Risk model inside the Streamlit runtime.
"""

import os
import torch
import streamlit as st
import xgboost as xgb
from transformers import AutoTokenizer, AutoModelForSequenceClassification

@st.cache_resource
def load_production_models():
    """Load FinBERT tokenizer and model for production sentiment analysis"""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
    nlp_model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert").to(device)
    return tokenizer, nlp_model, device

@st.cache_resource
def load_production_xgb_model():
    """Load the serialized Indian Market XGBoost Risk Model into server memory"""
    # Look for the model file generated by modeling.py
    model_path = os.path.join("models", "xgboost_risk_model.json")
    if not os.path.exists(model_path):
        raise FileNotFoundError(
            f"[-] Institutional Model Weights missing at {model_path}. Please execute modeling.py first."
        )
    
    model = xgb.XGBRegressor()
    model.load_model(model_path)
    return model

def get_models():
    """Retrieve cached deep learning weights to prevent RAM leakage during dashboard re-runs"""
    return load_production_models()